### ISSUE TITLE
Step 8. "TypeError: 'NoneType' object has no attribute '__getitem__'"

### ISSUE THREAD

**Issue by mohanwugupta** [onnela-lab/beiwe-backend#42] opened 2018-06-26 21:42 UTC
Hi, I'm not sure what the issue is. I've tried the purge and deleting created files a few times. I'm not sure if this would cause an issue but the files are housed on a cloud (Box). Error below:

INFO cluster-management: writing database credentials to disk, database address will be added later.
INFO cluster-management: database credentials have been written to /Users/CCNLAB/Box Sync/Cognitive and Clinical Neuroscience Lab/Projects/Longitudinal/Beiwe/beiwe-backend/cluster_management/environment_configuration/longitudinal_database_credentials.json
INFO cluster-management: Creating RDS Postgres database named longitudinal-database
Traceback (most recent call last):
  File "launch_script.py", line 534, in <module>
    do_create_environment()
  File "launch_script.py", line 310, in do_create_environment
    create_new_rds_instance(name)
  File "/Users/CCNLAB/Box Sync/Cognitive and Clinical Neuroscience Lab/Projects/Longitudinal/Beiwe/beiwe-backend/cluster_management/deployment_helpers/aws/rds.py", line 219, in create_new_rds_instance
    Engine=engine['Engine'],  # will be "postgres"
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jhlee22** [comment] 2018-08-31 17:59
Hello,

I also encountered the same error.  In this case, the files are housed on a local computer (Mac) and I also tried to create files a few times using difference branches.  It appears that a security group on AWS was created.  I would appreciate any insight anyone can provide regarding this issue.

**Comment by biblicabeebli** [comment] 2018-08-31 19:32
I just pushed an minor addition onto master, commit 55afe3a16e1c9b34501f3655288b5c19c663a083, so that the system should now provides a useful error message when this situation occurs.

This appears to be a situation where AWS failed to return correct database service information.  This is possibly a region specific error, or AWS has changed their database service information so dramatically that the logic to identify the most recent version of postgres has broken.

Let me know what your region is, but I also recommend trying in a different region.

**Comment by jhlee22** [comment] 2018-08-31 20:00
Hello,

Thanks a lot for getting back to me.  I am using "us-east-1.”  I will also try your edit to see if I can get a more specific error message.

Thanks again!

Junghee

**Comment by ccraddock** [comment] 2018-09-01 06:36
The problem isn't that postgres has been removed, its that more databases have been added. The describe_db_engine_versions method (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.describe_db_engine_versions) only returns 100 database descriptors at a time, which only gets through oracle. This can be solved by either using the returned marker to 'page' through the results, or to use the 'Engine' parameter of the method to directly specify that it only return 'postgres' database engines.

**Comment by biblicabeebli** [comment] 2018-09-04 18:42
Hooray, a new and exciting failure mode...
Thanks for your work, let me know when you have it working, sorry about the inconvenience.

**Comment by biblicabeebli** [comment] 2018-10-25 23:16
This issue has been resolved in commit 72164257165803dc3dbcfbf184e83278caf4bcd6.

**Closed by biblicabeebli** 2018-10-25 23:16 UTC
