### ISSUE TITLE
AWS image installation (1 year old) does not collect data from smartphones 

### ISSUE THREAD

**Issue by yoni1961** [onnela-lab/beiwe-backend#170] opened 2020-10-26 09:33 UTC
Hi
Please help.
We have a AWS image installation (1 year old) does not collect data from smartphones.
It worked fine until 4 months ago.
Now, new users are shown on the system and all, but when attempting to download data, the files download empty!
Any suggestion on how to go about it? This happens with past (working) research, with new research that I start. Old data from past research does download OK. It seems that only newly collected data does not download!
Please assist on the best way to go about it (upgrade? for example and if so how?)
Best
Yonathan

**Comment by biblicabeebli** [comment] 2020-10-29 23:43
Hello!
If you are on the old python 2.7 AMI version of Beiwe then the data processing code operates with a global lock so that data processing runs do not overlap.  To attempt to restart it you need to unlock that lock.

If you ssh onto the server and run the db command you should be dropped into an iPython shell.

Try either of these commands, the second may not exist on the old version of the codebase, the first shoooouuld work... I think.
`FileProcessLock.objects.all().delete()`
or
`FileProcessLock.unlock()`

This will allow the next data processing run to start.
However, if you have an issue that is causing data processing to fail every time it is run that will probably occur again.

If you are hitting out of memory scenarios then there are several options, all of them somewhat complex.  Let us know how that goes.

**Comment by yoni1961** [comment] 2020-11-10 17:33
Dear Eli
Firstly, thank you again for your help!!!
We tried all your suggestions as you can see below (we do have the older Python....) - without success- Please see a screen below (image.png)


Later, me and my system expert (Mr. Amit Joshi) spent a few hours on this.
1. We started a new study.
2. We downloaded and installed the app on a new mobile device (all android...)
3. The system created the user and the relevant folders - we see those on the S3 buckets  (see screen shot) but collected data only on the first 2 minutes and nothing else, despite a number of trails that lasted for about 30 minutes of refreshes etc. so it looks that the data is not being collected.
4. When we download that data that has been collected (on this and on a past study from the last month), we get gibberish data on the CSV file (see two files attached....)
5. Lastly, when we download all the raw data (of the single user) of this new file, the zip file downloads with a call for a password and only 1k in size (empty...).

How do you make sense of this?  
Is it possible that we need a newer IWS image file of the Beiwe system? Could it be a compatibility issue of the server and the client? If we need a newer version version of the AWS image were can we get it?

Please advise... 

Yonathan

**Comment by yoni1961** [comment] 2020-11-10 17:35
![Screen Capture_select-area_20201110223434](https://user-images.githubusercontent.com/2241383/98709938-b213cb00-238b-11eb-8f46-2784cfc6f53c.png)
https://mail.google.com/mail/u/0?ui=2&ik=e5e3bbf20d&attid=0.0.2&permmsgid=msg-a:r-2632763445295953208&th=175b32b156b16af8&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ-wM88Iuh


https://mail.google.com/mail/u/0?ui=2&ik=e5e3bbf20d&attid=0.0.3&permmsgid=msg-a:r-2632763445295953208&th=175b32b156b16af8&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ_NTkflzIF25Kv-WVVNhfGk095ItVltEIceQLRkfgxTSQ-0osynWzRPkAiOxC5PX7dDsMjnDnj4uLlY5Ss3BDF6TrGxQxhHlLbNEzEGgxnE0alD9Cf-C9yyO-Y&disp=emb&realattid=ii_khbvlal92LJ6p6xW6FUkm4kVmJt3QxkISP8YsbZDTrYEjqKJGX0w2d9N6rTMvN6hdPN8DJtsOmkI4V1qZl9a2LOQps4iBuzAUDaLJuJrkHinROkxI-fhypZeE0&disp=emb&realattid=ii_khbvkko51

**Comment by biblicabeebli** [comment] 2020-11-18 03:53
There's a lot here and my abilitiy to help is limited.

You seem to be running the ancient of the shell, one for the old mongodb database.  Start by running `python manage.py shell_plus` or `python manage.py shell` (second one requires some python knowledge and imports, shell_plus does some nice automatic things for you) and running the command you have tried. That command is for the django database, not the mongo database.  The error you are getting in that shell is that you haven't imported FileProcessLock.

The AMI is horribly out of date and is somewhat ... unsolvable.  There are fundamental issues with maintaining a system image because server configuration is not something we can _push_ out on the AMI, the system administrator needs to manually administrate configuration changes.  The beiwe cluster allows us to blow away and spin up new data processing servers, and consequently there are numerous sysadmin-style changes somewhat frequently.  I'm sorry, but I don't know how to resolve this short  of getting up up on a cluster deployment.

I believe you have contacted me by email, but if not feel free.  I will try to help you out when I have time.

I need to close this issue because the problem is not resolvable within the context of the forum.

**Closed by biblicabeebli** 2020-11-18 03:53 UTC
